import { useState } from "react";
import Error from "../error/Error";
// import { progress } from "mocha/lib/reporters";

const Image = () => {
    const [prompt, setPrompt] = useState("");
    const [seed, setSeed] = useState(42);
    const [guidanceScale, setGuidanceScale] = useState(7.5);
    const [numInfSteps, setNumInfSteps] = useState(10);
    const [error, setError] = useState("");
    const [img, setImg] = useState(null);
    const [promptImg, setPromptImg] = useState(null);
    const [loadingImg, setLoadingImg] = useState(false);

    const cleanFormData = () => {
        setPrompt("");
        setSeed(42);
        setGuidanceScale(7.5);
        setNumInfSteps(5);
        setLoadingImg(false);
        setError("");
    }

    const generateImage = async (event) => {
        const requestOptions = {
            method: "GET",
            headers: {"Content-Type": "application/json"},
        };

        setLoadingImg(true);

        const response = await fetch(`/api/generate/?prompt=${prompt}&num_inference_steps=${numInfSteps}&guidance_scale=${guidanceScale}&seed=${seed}`, requestOptions);

        if (!response.ok) {
            setError("Oops! Something went wrong generating the image.");
        } else {
            const imageBlob = await response.blob();
            const imageObjectUrl = URL.createObjectURL(imageBlob);
            setImg(imageObjectUrl);
            setPromptImg(prompt);
            cleanFormData();
        }
    }

    const submitForm = (event) => {
        event.preventDefault();
        setImg(null);
        setPromptImg(null);
        generateImage();
    }

    return (
        <>
        <div className="columns is-vcentered">
            <div className="column">
                <form className="box" onSubmit={submitForm}>
                    <h1 className="title has-text-centered is-4">Generate an Image with the Stable Diffusion Algorithm!</h1>
                    
                    <div className="field">
                        <label className="label">Prompt</label>
                        <div className="control">
                            <input 
                                type="text" 
                                placeholder="Enter your prompt to generate an image!" 
                                value={prompt} 
                                onChange={(event) => setPrompt(event.target.value)}
                                className="textarea"
                                required
                            />
                        </div>
                    </div>

                    <div className="field">
                        <label className="label">Seed</label>
                        <div className="control">
                            <input 
                                type="text" 
                                placeholder="seed" 
                                value={seed} 
                                onChange={(event) => setSeed(event.target.value)} 
                                className="input"
                            />
                        </div>
                    </div>

                    <div className="field">
                        <label className="label">Guidance Scale</label>
                        <div className="control">
                            <input 
                                type="text" 
                                placeholder="guidancescale" 
                                value={guidanceScale} 
                                onChange={(event) => setGuidanceScale(event.target.value)} 
                                className="input" 
                            />
                        </div>
                    </div>
                    
                    <div className="field">
                        <label className="label">Number of Inference Steps</label>
                        <div className="control">
                            <input 
                                type="text" 
                                placeholder="Larger values demand higher processing but may result in better quality."
                                value={numInfSteps} 
                                onChange={(event) => setNumInfSteps(event.target.value)}
                                className="input" 
                            />
                        </div>
                    </div>
                        <Error message={error} />
                    <br />
                    <button className="button is-primary" type="submit">Generate Image</button>
                </form>
            </div>
            <div className="column">
            { img ? (
            <figure>
                <img src={img} alt="Generated by Stable Diffusion" />
                <figcaption>{promptImg}</figcaption>
            </figure> )
                : <></>
            }
            { loadingImg ? (
                <progress className="progress is-small is-primary" max="100">Loading</progress>
            ) : <></>
            }
            </div>
        </div>
        </>
    )
}

export default Image;